<?php

namespace Database\Seeders;

use App\Models\FeeSlipTemplate;
use Illuminate\Database\Seeder;

class FeeSlipTemplateSeeder extends Seeder
{
    public function run(): void
    {
        FeeSlipTemplate::truncate();

        // ── 1. KIU Style (Active) ────────────────────────────────────────────────
        FeeSlipTemplate::create([
            'name'                  => 'KIU Style (Default)',
            'variant'               => 'kiu',
            'is_active'             => true,
            'orientation'           => 'landscape',
            'college_name'          => 'Jinnah School & Degree College Astore',
            'college_subtitle'      => '(EIDGAH ASTORE)',
            'college_short_name'    => 'JDCA',
            'logo_path'             => null,
            'primary_color'         => '#009999',
            'accent_color'          => '#1a56db',
            'text_color'            => '#111111',
            'bank_name'             => 'KCBL',
            'bank_account'          => '0368421',
            'bank_account_title'    => 'Jinnah School & Degree College Astore',
            'bank_branch'           => 'Eidgah Astore',
            'ref_prefix'            => '2024-JDCA',
            'bill_prefix'           => '',
            'copies'                => ['Bank Copy', 'Accounts Copy', 'Student Copy'],
            'fee_display_mode'      => 'dynamic',
            'fee_items'             => null,
            'show_barcode'          => true,
            'show_watermark'        => false,
            'watermark_text'        => null,
            'show_in_words'         => true,
            'show_depositor_fields' => true,
            'show_ref_no'           => true,
            'show_consumer_no'      => true,
            'show_accountant_sig'   => false,
            'instructions'          => "• Submit at any KCBL branch or via KCBL Mobile App.\n• Keep this copy as proof of payment after bank stamp / online receipt.\n• Late fine applicable after due date. Expired challan will not be accepted.",
            'footer_text'           => 'Hunza Printing Press Gilgit. Ph: 05811-451868-69',
        ]);

        // ── 2. Classic JDCA Style ────────────────────────────────────────────────
        FeeSlipTemplate::create([
            'name'                  => 'Classic JDCA Style',
            'variant'               => 'classic',
            'is_active'             => false,
            'orientation'           => 'portrait',
            'college_name'          => 'Jinnah School & Degree College Astore',
            'college_subtitle'      => '(EIDGAH ASTORE)',
            'college_short_name'    => 'JDCA',
            'logo_path'             => null,
            'primary_color'         => '#2e7d32',
            'accent_color'          => '#1b5e20',
            'text_color'            => '#111111',
            'bank_name'             => 'KCBL',
            'bank_account'          => '0368421',
            'bank_account_title'    => 'Jinnah School & Degree College Astore',
            'bank_branch'           => 'Eidgah Astore',
            'ref_prefix'            => '2024-JDCA',
            'bill_prefix'           => '',
            'copies'                => ['Bank Copy', 'Accounts Copy', 'Student Copy'],
            'fee_display_mode'      => 'static',
            'fee_items'             => [
                ['label' => 'Admission Fee'],
                ['label' => 'University Reg. Fee'],
                ['label' => 'College Security Fee'],
                ['label' => 'Library Fee'],
                ['label' => 'Laboratory Security Fee'],
                ['label' => 'College ID Card'],
                ['label' => 'Certificate Verification'],
                ['label' => 'Tuition Fee'],
                ['label' => 'Medical Fund'],
                ['label' => 'Library Fund/Fee'],
                ['label' => 'Sports Fund/Student Activity'],
                ['label' => 'Winter Charges'],
                ['label' => 'Examination Fee'],
                ['label' => 'Seminar & Workshop'],
                ['label' => 'Computer Facility Charges'],
                ['label' => 'Student Study Tours'],
                ['label' => 'Subject Enrollment'],
            ],
            'show_barcode'          => false,
            'show_watermark'        => false,
            'watermark_text'        => null,
            'show_in_words'         => true,
            'show_depositor_fields' => true,
            'show_ref_no'           => true,
            'show_consumer_no'      => false,
            'show_accountant_sig'   => true,
            'instructions'          => "• Submit at any KCBL branch.\n• Keep this copy as proof of payment.\n• Late fine applicable after due date.",
            'footer_text'           => 'Hunza Printing Press Gilgit. Ph: 05811-451868-69',
        ]);

        // ── 3. Modern Blue ───────────────────────────────────────────────────────
        FeeSlipTemplate::create([
            'name'                  => 'Modern Blue',
            'variant'               => 'modern',
            'is_active'             => false,
            'orientation'           => 'landscape',
            'college_name'          => 'Jinnah School & Degree College Astore',
            'college_subtitle'      => '(EIDGAH ASTORE)',
            'college_short_name'    => 'JDCA',
            'logo_path'             => null,
            'primary_color'         => '#1e40af',
            'accent_color'          => '#3b82f6',
            'text_color'            => '#111827',
            'bank_name'             => 'KCBL',
            'bank_account'          => '0368421',
            'bank_account_title'    => 'Jinnah School & Degree College Astore',
            'bank_branch'           => 'Eidgah Astore',
            'ref_prefix'            => '2024-JDCA',
            'bill_prefix'           => '',
            'copies'                => ['Bank Copy', 'Accounts Copy', 'Student Copy'],
            'fee_display_mode'      => 'dynamic',
            'fee_items'             => null,
            'show_barcode'          => true,
            'show_watermark'        => false,
            'watermark_text'        => null,
            'show_in_words'         => true,
            'show_depositor_fields' => true,
            'show_ref_no'           => true,
            'show_consumer_no'      => true,
            'show_accountant_sig'   => false,
            'instructions'          => "• Submit at any KCBL branch or via KCBL Mobile App.\n• Keep this copy as proof of payment after bank stamp / online receipt.\n• Late fine applicable after due date.",
            'footer_text'           => 'Hunza Printing Press Gilgit. Ph: 05811-451868-69',
        ]);

        // ── 4. Minimal B&W ───────────────────────────────────────────────────────
        FeeSlipTemplate::create([
            'name'                  => 'Minimal B&W',
            'variant'               => 'minimal',
            'is_active'             => false,
            'orientation'           => 'portrait',
            'college_name'          => 'Jinnah School & Degree College Astore',
            'college_subtitle'      => 'Eidgah, Astore, Gilgit-Baltistan',
            'college_short_name'    => 'JDCA',
            'logo_path'             => null,
            'primary_color'         => '#111111',
            'accent_color'          => '#444444',
            'text_color'            => '#111111',
            'bank_name'             => 'KCBL',
            'bank_account'          => '0368421',
            'bank_account_title'    => 'Jinnah School & Degree College Astore',
            'bank_branch'           => 'Eidgah Astore',
            'ref_prefix'            => '2024-JDCA',
            'bill_prefix'           => '',
            'copies'                => ['Bank Copy', 'Accounts Copy', 'Student Copy'],
            'fee_display_mode'      => 'dynamic',
            'fee_items'             => null,
            'show_barcode'          => false,
            'show_watermark'        => false,
            'watermark_text'        => null,
            'show_in_words'         => true,
            'show_depositor_fields' => true,
            'show_ref_no'           => true,
            'show_consumer_no'      => false,
            'show_accountant_sig'   => true,
            'instructions'          => "• Submit at any KCBL branch.\n• Keep this copy as proof of payment.\n• Late fine applicable after due date.",
            'footer_text'           => null,
        ]);
    }
}
