[program:jdca-queue]
process_name=%(program_name)s_%(process_num)02d
directory=/var/www/jdca
command=php /var/www/jdca/artisan queue:work redis --queue=default --sleep=3 --tries=3 --timeout=120 --max-time=3600
autostart=true
autorestart=true
stopasgroup=true
killasgroup=true
user=www-data
numprocs=1
redirect_stderr=true
stdout_logfile=/var/www/jdca/storage/logs/queue-worker.log
stdout_logfile_maxbytes=20MB
stdout_logfile_backups=10
stopwaitsecs=3600
environment=APP_ENV="production"
