@extends('layouts.teacher-portal')
@section('title', 'My Salary')
@section('content')

<div class="space-y-6">
  <div>
    <h2 class="text-xl font-bold text-gray-900">My Salary</h2>
    <p class="mt-1 text-sm text-gray-500">Your monthly salary payment history.</p>
  </div>

  {{-- Summary cards --}}
  <div class="grid grid-cols-1 gap-4 sm:grid-cols-2">
    <div class="rounded-2xl bg-emerald-50 p-5 ring-1 ring-emerald-200">
      <div class="mb-2 text-xs font-bold uppercase tracking-wide text-stone-400">Total Received</div>
      <div class="text-2xl font-bold text-emerald-700">Rs. {{ number_format($summary['total_paid'], 0) }}</div>
    </div>
    <div class="rounded-2xl bg-amber-50 p-5 ring-1 ring-amber-200">
      <div class="mb-2 text-xs font-bold uppercase tracking-wide text-stone-400">Pending</div>
      <div class="text-2xl font-bold text-amber-700">Rs. {{ number_format($summary['total_pending'], 0) }}</div>
    </div>
  </div>

  @if($payments->isEmpty())
    <div class="rounded-2xl bg-white p-16 text-center" style="border: 1px solid #e5e7eb">
      <div class="mx-auto mb-4 flex h-14 w-14 items-center justify-center rounded-2xl bg-stone-100">
        <svg class="h-7 w-7 text-stone-300" fill="none" stroke="currentColor" viewBox="0 0 24 24" stroke-width="1.5"><path stroke-linecap="round" stroke-linejoin="round" d="M12 8c-1.657 0-3 .895-3 2s1.343 2 3 2 3 .895 3 2-1.343 2-3 2m0-8c1.11 0 2.08.402 2.599 1M12 8V7m0 1v8m0 0v1m0-1c-1.11 0-2.08-.402-2.599-1M21 12a9 9 0 11-18 0 9 9 0 0118 0z"/></svg>
      </div>
      <h3 class="mb-1 font-semibold text-stone-500">No Salary Records Yet</h3>
      <p class="text-sm text-stone-400">Your salary payments will appear here once generated by the admin.</p>
    </div>
  @else
    <div class="rounded-2xl bg-white" style="border: 1px solid #e5e7eb">
      <div class="divide-y divide-stone-100">
        @foreach($payments as $p)
          @php
            $isPaid = $p->payment_status === 'paid';
          @endphp
          <div class="flex flex-wrap items-center justify-between gap-3 p-5">
            <div>
              <p class="font-semibold text-stone-800">{{ $p->month_label }}</p>
              <p class="mt-0.5 font-mono text-xs text-stone-400">{{ $p->reference_no }}</p>
            </div>
            <div class="flex items-center gap-6 text-sm">
              <div class="text-right">
                <p class="text-[10px] uppercase text-stone-400">Net Amount</p>
                <p class="font-semibold text-stone-700">Rs. {{ number_format($p->net_amount, 0) }}</p>
              </div>
              @if($isPaid)
                <div class="text-right">
                  <p class="text-[10px] uppercase text-stone-400">Paid On</p>
                  <p class="font-semibold text-stone-500">{{ $p->payment_date?->format('d M Y') ?? '—' }}</p>
                </div>
              @endif
              <span class="rounded-full px-2.5 py-1 text-xs font-bold capitalize {{ $isPaid ? 'bg-emerald-100 text-emerald-700' : 'bg-amber-100 text-amber-700' }}">
                {{ $p->payment_status }}
              </span>
            </div>
          </div>
        @endforeach
      </div>
    </div>
  @endif
</div>
@endsection
